### ISSUE TITLE
BLE

### ISSUE THREAD

**Issue by Andersbhc** [Jafre13/AndroidExamples#3]
Hello, we need to connect to a BLE device, does anybody know how to do this?

**Comment by Jafre13** [comment]
Sorry for the late answer, unfortunately i had some notifications turned off, so it didn't pop up.

An introduction as how you can enable ble devices in android can be found on their wiki. In general they work the same as regular bluetooth devices, but has a few more options.

check out this link for a quick description as how to make it work, if you still have problems, feel free to contact me and i will try to make some example code for you
https://developer.android.com/guide/topics/connectivity/bluetooth-le.html#terms
